name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
      concurrency:
        group: ${{ github.ref }}_lint
        cancel-in-progress: true

      runs-on: macos-13
      steps:
        - uses: actions/checkout@v4

        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: latest-stable

        - uses: ruby/setup-ruby@v1

        - name: Install Bundler
          run: gem install bundler

        - name: Install Gems
          run: bundle install

        - name: Run Linter
          run: bundle exec fastlane lint

  test:
    concurrency:
        group: ${{ github.ref }}_tests
        cancel-in-progress: true

    needs: lint
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        run: bundle install

      - name: Run Tests
        run: bundle exec fastlane unit_tests
